### PR TITLE
Vet clinic database: create animals table

### PR DESCRIPTION
**Pull request by MarcoOquendoC**
# [Vet clinic database: create animals table](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_create_tables.md)

## Hi good reviewer,

I am not sure about the following line:
`SELECT * FROM animals WHERE weight_kg BETWEEN 10.4 AND 17.3;`
It works on integers but I tried with `BETWEEN 10.23 AND 15.04` and it only shows the one with 15.04kg
Kindly tell me if I did something wrong.

Patricio greeting

## These are the project requirements for this milestone:

Use [this template](https://github.com/microverseinc/curriculum-template-databases).
Create a database named vet_clinic.
Create a table named animals:
Copy the SQL commands into the schema.sql file.
Insert data:
Copy the SQL commands into the data.sql file.
Write queries:
Take a screenshot of the results of your queries.
Copy the SQL commands into the queries.sql file.
Add screenshots with the results of the queries to this Pull Request description.

image

image

### CODE REVIEW

**Review by muneebulrehman — APPROVED** [review]
Hi @MarcoOquendoC , 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥳
Congratulations! 🎉 

# Status: Approved✔️

## Highlights
- Descriptive PR
- Good documentation
- All queries run successfully.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MarcoOquendoC** [comment]
# Hi @muneebulrehman 

I am not sure about the following line:
`SELECT * FROM animals WHERE weight_kg BETWEEN 10.4 AND 17.3;`
It works on integers but I tried with `BETWEEN 10.23 AND 15.04` and it only shows the one with 15.04kg
Kindly tell me if I did something wrong.

**Comment by muneebulrehman** [comment]
Hey @MarcoOquendoC , from what I can see in the screenshot provided by you in the PR, you are getting two results when you run this query. And there are only two animals with weights between 10.23 and 17.3

**Comment by muneebulrehman** [comment]
Hey @MarcoOquendoC, from what I can see in the screenshot provided in the PR, when you run the query you are getting two results not one.

**Comment by MarcoOquendoC** [comment]
Thanks for you answer.
It shows 2 results but there should be 3 including the 10.23 result.

**Review by Mihndim2020 — COMMENTED** [review]
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
### Hi @MarcoOquendoC, 

### Good job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Descriptive Readme file

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

Congratulations-Memes-FEATURED



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can get to me on slack  using this handle @mihndim.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
