### PR TITLE
Vet clinic database: query multiple tables

### PR DESCRIPTION
**Pull request by MarcoOquendoC**
# [Vet clinic database: query multiple tables](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_query_multiple_tables.md)

"## Hi good reviewer,

Patricio greeting

### schema.sql file.
- Create a table named owners
- Create a table named species
- Remove column species
- Add column species_id which is a foreign key referencing species table
- Add column owner_id which is a foreign key referencing the owners table

### data.sql file
- Insert data into the owners table:
- Insert data into the species table:
- Modify your inserted animals so it includes the species_id value:
- Modify your inserted animals to include owner information (owner_id):

### queries.sql file
- Write queries (using JOIN)
- What animals belong to Melody Pond?
- List of all animals that are pokemon (their type is Pokemon).
- List all owners and their animals, remember to include those that don't own any animal.
- How many animals are there per species?
- List all Digimon owned by Jennifer Orwell.
- List all animals owned by Dean Winchester that haven't tried to escape.
- Who owns the most animals?

image

Queries
image

### CODE REVIEW

**Review by brytebee — APPROVED** [review]
Hi, @MarcoOquendoC👋,

##

### Highlights💡
- Good commit message.✔️ 
- Good PR Summary.✔️
- Great schema design.✔️
- Well-written queries.✔️
- App functions as it should.✔️

#

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 



Good luck! 🎉 

##

###  **Optional Suggestions:**
- N/A

------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by peterrobert — COMMENTED** [review]
### INVALID 🛑 

Great work for your effort to submit a pull request for review. However, I can not continue to review your project for the following reasons.

- [x]  You have submitted an already approved project.
- [x]  Your branch is already merged with the develop branch.

**Comment by MarcoOquendoC** [comment]
Hi @peterrobert,

I am repeating this week.
Should I create a new repo or just create a new branch/pull request?

Thanks in advance.

Marco.

**Comment by peterrobert** [comment]
@MarcoOquendoC  Kindly create a new branch

**Pull request merged**
